### ISSUE TITLE
Core Developer Docs Upgrade

### ISSUE THREAD

**Issue by jacobcreech** [solana-developers/developer-experience#11]
The beginning of the [core developer docs](https://docs.solana.com/developing/programming-model/overview) needs an overhaul.

Issue for tracking: https://github.com/solana-labs/solana/issues/26699

**Comment by balexander123** [comment]
Hello @jacobcreech I would like to help out with this issue.  What to know more about whats involved and how to contribute

**Comment by nickfrosty** [comment]
Docs migration completed
