### ISSUE TITLE
Destroy an Account

### ISSUE THREAD

**Issue by buffalojoec** [solana-developers/developer-experience#2]
This is a Byte Video. The code can be found [here](https://github.com/solana-developers/program-examples) in the `basics/destroy-account` folder. If the folder does not exist yet, the demo must be created! See Issue #26 .   

We want to demonstrate zero-ing out an account's data, closing it, and reclaiming the SOL (in both Native & Anchor)

**Comment by jacobcreech** [comment]
Anyone is welcome to create a video or short content on this as well
