### ISSUE TITLE
Solana 101 Workshop dApp - Solana Twitter

### ISSUE THREAD

**Issue by buffalojoec** [solana-developers/developer-experience#22]
- [ ] Finalize CSS formatting
- [ ] Remove Anchor RPC methods from `util.ts` and create separate template

This will allow us to distribute the template to participants and then we can build the RPC calls during the workshop. That way, we don't have to worry about wasting time in the workshop trying to build & configure all of the UI components.

Joe will be presenting this workshop:   
KU Hackathon - Tuesday, August 2nd 8:15 AM (CT)
mtnDAO - Tuesday August 9th (Time TBD)

**Comment by Haledevx** [comment]
> * [ ]  Finalize CSS formatting
> * [ ]  Remove Anchor RPC methods from `util.ts` and create separate template
> 
> This will allow us to distribute the template to participants and then we can build the RPC calls during the workshop. That way, we don't have to worry about wasting time in the workshop trying to build & configure all of the UI components.
> 
> Joe will be presenting this workshop: KU Hackathon - Tuesday, August 2nd 8:15 AM (CT) mtnDAO - Tuesday August 9th (Time TBD)


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/
