### ISSUE TITLE
Transfer an Account's Ownership

### ISSUE THREAD

**Issue by buffalojoec** [solana-developers/developer-experience#3]
This is a Byte Video. The code can be found [here](https://github.com/solana-developers/program-examples) in the `basics/transfer-account-owner` folder. If the folder does not exist yet, the demo must be created! See Issue #26 .   

We want to explain & show how to transfer an account's owner from one wallet to another (in both Native & Anchor)

**Comment by jacobcreech** [comment]
Anyone is welcome to create a video or short content on this as well
