### ISSUE TITLE
Return Data Tutorial

### ISSUE THREAD

**Issue by jacobcreech** [solana-developers/developer-experience#30]
You can return data via transactions now. We should have a video demonstration + documentation on how to use return data.

[Return Data Docs](https://docs.solana.com/proposals/return-data)
[Example Usage](https://www.anchor-lang.com/docs/cross-program-invocations#return-data-size-limit-workarounds)

**Comment by stephenhuh** [comment]
love it. i can probably tackle this.

**Comment by jacobcreech** [comment]
@stephenhuh Please do! This is open for anyone
