### ISSUE TITLE
Hot-Reloading Programs

### ISSUE THREAD

**Issue by jacobcreech** [solana-developers/developer-experience#31]
Let's get a tool built that Hot-reloads programs on Solana for local development. You could think of something like [Nodemon](https://www.npmjs.com/package/nodemon) on program deployments.

Let's get it working for both Anchor and Native if possible. Priority Anchor

**Comment by buffalojoec** [comment]
Didn't Frostbutter have something in the barrel for this?

**Comment by jacobcreech** [comment]
@jpcaulfi not fully realized just yet

**Comment by anoushk1234** [comment]
@jacobcreech so on save compile and deploy to locanet?

**Comment by jacobcreech** [comment]
@anoushk1234, yes that is correct. Ideally leveraging something super fast like Solana playground APIs

**Comment by anoushk1234** [comment]
> @anoushk1234, yes that is correct. Ideally leveraging something super fast like Solana playground APIs

Seems easy enough to build although i wanted to optimise it a bit further, instead of deploying the entire program to the chain is it possible to compare changes and only deploy those?

**Comment by jacobcreech** [comment]
> is it possible to compare changes and only deploy those?

Not in the current state. Would be a cool feature to have though

**Comment by acheroncrypto** [comment]
This is now possible with https://github.com/acheroncrypto/watchso

It also checks and updates program ids and has support for Native, Anchor and Seahorse.
