### ISSUE TITLE
Create a Seahorse program example

### ISSUE THREAD

**Issue by jacobcreech** [solana-developers/developer-experience#32]
We have a bunch of program examples in Anchor and Native found in the [program-examples repo](https://github.com/solana-developers/program-examples). We need to add [Seahorse-lang](https://seahorse.dev/) examples as well for those that want to use python.

Do participate in this issue, add a Seahorse-lang version of one of the existing programs.

**Comment by cdhiraj40** [comment]
@jacobcreech I would give it a try and write some examples in sea-horse for [program-examples repo](https://github.com/solana-developers/program-examples).

**Comment by jacobcreech** [comment]
@cdhiraj40 that's great! Any examples on the repo that don't have the seahorse counterpart would be greatly appreciated!

**Comment by mikebrownie** [comment]
A potential gap is using PDAs (Program Derived Addresses) w/ Seahorse. Currently trying to figure this out. 

Anchor example: https://www.anchor-lang.com/docs/pdas
