### ISSUE TITLE
Get token along with metadata

### ISSUE THREAD

**Issue by nemanjab17** [solana-developers/developer-experience#33]
Would be great to have a tutorial/code snippets on how to fetch token and its metadata

**Comment by cryptoloutre** [comment]
Hi @nemanjab17 & @jacobcreech, here is the tutorial I propose https://github.com/cryptoloutre/fetch-token-and-its-metadata.
I don't know if it's appropriate, so don't hesitate to give me suggestions to improve it.

**Comment by jacobcreech** [comment]
@cryptoloutre this is a great guide! Do you have a good place to put it outside of a git repo? Hackmd, medium, etc for publishing

**Comment by cryptoloutre** [comment]
@jacobcreech Thanks, I made a medium https://medium.com/@laloutre/how-to-fetch-the-metadata-of-a-spl-token-cc969791d978
