### ISSUE TITLE
Reallocate an Account's Data

### ISSUE THREAD

**Issue by buffalojoec** [solana-developers/developer-experience#4]
This is a Byte Video. The code can be found [here](https://github.com/solana-developers/program-examples) in the `basics/reallocate-account-data` folder. If the folder does not exist yet, the demo must be created! See Issue #26 .   

We want to show how to use the `realloc` method to reallocate an account's data (in both Native & Anchor)

(This may be identical to Issue #18 depending on requirements)

**Comment by jacobcreech** [comment]
Anyone is welcome to create a video or short content on this as well
